version: "3"

services:
  db:
    image: mysql:8.0.22
    container_name: app-db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3308:3306
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        PHP_VERSION: ${PHP_VERSION}
        REMOTE_WORKING_DIR: ${REMOTE_WORKING_DIR}/app/
        TIMEZONE: ${TIMEZONE}
    container_name: app-php
    volumes:
      - ${LOCAL_WORKING_DIR}/app/:${REMOTE_WORKING_DIR}/app/
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    volumes:
      - ${LOCAL_WORKING_DIR}/:${REMOTE_WORKING_DIR}/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  db_app:

networks:
  app-network:
